{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "artemis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "artemis.labels.standard" . | indent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-name: {{ include "artemis.name" . }}-route
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- if .Values.ingress.hostName }}
    - host: {{ .Values.ingress.hostName }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "artemis.fullname" . }}-master
                port:
                    number: 8161
{{- if .Values.ingress.tls }}
  tls:
    - secretName: {{ .Values.ingress.tlsSecret }}
      {{- if .Values.ingress.hostName }}
      hosts:
        - {{ .Values.ingress.hostName }}
      {{- end }}
{{- end }}
{{- end }}
