apiVersion: v1
kind: Service
metadata:
  annotations:
    # Exclude unready slave nodes from DNS
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "false"
  name: {{ include "artemis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "artemis.labels.standard" . | indent 4 }}
spec:
  ports:
  - name: http
    port: 8161
    targetPort: http
  - name: core
    port: 61616
    targetPort: core
  - name: amqp
    port: 5672
    targetPort: amqp
  - name: exporter
    port: 9404
    targetPort: exporter
  {{- if not (eq .Values.service.type "HostPort") }}
  type: {{ .Values.service.type }}
  {{- end }}
  selector:
    app: {{ template "artemis.name" . }}
    release: {{ .Release.Name | quote }}
  sessionAffinity: "ClientIP"
