{{- if .Values.slaves }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    # Make sure DNS is resolvable during initialization.
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: {{ include "artemis.fullname" . }}-slave
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "artemis.labels.standard" . | indent 4 }}
    component: artemis-node
spec:
  ports:
  - name: http
    port: 8161
    targetPort: http
  - name: core
    port: 61616
    targetPort: core
  - name: amqp
    port: 5672
    targetPort: amqp
  - name: exporter
    port: 9404
    targetPort: exporter
  {{- if not (eq .Values.service.type "HostPort") }}
  type: {{ .Values.service.type }}
  {{- end }}
  publishNotReadyAddresses: true
  selector:
    app: {{ template "artemis.name" . }}
    release: {{ .Release.Name | quote }}
    component: slave
{{- end }}
